Fix expected string in test_check_command
tests/unit/test_cli.py::test_check_command FAILED                                                                                                                                  [100%]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    def test_check_command():
        result = _call_colin(check)
        expected_output1 = "Usage: check [OPTIONS] TARGET"
        expected_output2 = 'Error: Missing argument "TARGET"'
        assert result.exit_code == 2
        assert expected_output1 in result.output
>       assert expected_output2 in result.output
E       assert 'Error: Missing argument "TARGET"' in "Usage: check [OPTIONS] TARGET\nTry 'check -h' for help.\n\nError: Missing argument 'TARGET'.\n"
E        +  where "Usage: check [OPTIONS] TARGET\nTry 'check -h' for help.\n\nError: Missing argument 'TARGET'.\n" = <Result SystemExit(2)>.output

tests/unit/test_cli.py:48: AssertionError