Fix tests execution on older kernel
The mount option metacopy-up was added into kernel 4.19.
and therefore podman build failed on older kernel

[root@d4d41c073ff2 src]# podman  build -t colin-labels -f Dockerfile /src/tests/data
Error: could not get runtime: failed to mount overlay for metacopy check: invalid argument
[root@d4d41c073ff2 src]# uname -a
Linux d4d41c073ff2 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

https://github.com/containers/libpod/issues/3243#issuecomment-518031505